constants:
  job_name:
    build_java_maven: buildJavaMaven
    test_java_maven : testJavaMaven
    sonar_cloud_scan: sonar_cloud_scan
    registry        : registry
    deploy          : deploy


  job_definition:
    stages_java: ["{{test_java_maven}}", "{{build_java_maven}}", "{{sonar_cloud_scan}}", "{{registry}}", "{{deploy}}"]