constants:
  job_name:
    buildJavaMaven: buildJavaMaven
    testJavaMaven: testJavaMaven
    sonarCloudScan: sonarCloudScan
    registry: registry
    deploy: deploy

  job_definition:
    stages_java:
      [
        "{{testJavaMaven}}",
        "{{buildJavaMaven}}",
        "{{sonarCloudScan}}",
        "{{registry}}",
        "{{deploy}}",
      ]
