
name: entrypoint 

on:
  workflow_call:

jobs:
  entryPointJavaMaven:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'
      - name: Get artifactId
        id: getArtifactId
        run: |
          export ARTIFACTID=$( mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout )
          echo "artifactId=$ARTIFACTID" >> $GITHUB_OUTPUT
      - name: Get version
        id: getVersion
        run: |
          export VERSION=$( mvn help:evaluate -Dexpression=project.version -q -DforceStdout )
          echo "version=$VERSION" >> $GITHUB_OUTPUT
    outputs:
      artifactId: ${{ steps.getArtifactId.outputs.artifactId }}
      version   : ${{ steps.getVersion.outputs.version }}
      branchName: ${{ github.ref_name }}
  
  