
name: buildJavaMaven

on:
  workflow_call:

jobs:
  buildJavaMaven:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'
      
      - name: mvnPackage
        run: mvn package -DskipTests