
name: buildJavaMaven

on:
  workflow_call:

jobs:
  buildJavaMaven:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'
          
      - name: mvnTest
        run: mvn verify test
      
      - name: mvnPackage
        run: mvn package -DskipTests
      
      - name: sonarCloudScan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ env.SONAR_TOKEN }}
        with:
          projectBaseDir: src/
          args: >
            -Dsonar.organization=interlinehub
            -Dsonar.projectKey=interlinehub_${{ github.event.artifactId }}
            -Dsonar.projectVersion=${{ github.event.version }}
            -Dsonar.coverage.jacoco.xmlReportPaths=../target/site/jacoco/jacoco.xml
            -Dsonar.java.binaries=../target/classes
            -Dsonar.coverage.exclusions=test/**