
name: buildJavaMaven

on:
  workflow_call:
    inputs:
      artifactId:
        required: true
        type: string
      version:
        required: true
        type: string
      branchName:
        required: true
        type: string

jobs:
  buildJavaMaven:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'
      
      - name: mvnPackage
        run: mvn package -DskipTests

      - name: Download Jacoco report
        uses: actions/download-artifact@v3
        with:
          name: jacoco-report
      
      - name: sonarCloudScan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: src/
          args: >
            -Dsonar.organization=interlinehub
            -Dsonar.projectKey=interlinehub_${{ inputs.artifactId }}
            -Dsonar.projectVersion=${{ inputs.version }}
            -Dsonar.coverage.jacoco.xmlReportPaths=jacoco.xml
            -Dsonar.java.binaries=../target/classes
            -Dsonar.coverage.exclusions=test/**