
name: constants

on:
  workflow_call:
    outputs:
      constants:
        description: "Constants to use in CICD pipeline"
        value: ${{ jobs.entryPoint.outputs.constants }}
      artifactId:
        description: "ArtifactID from descriptor"
        value: ${{ jobs.entryPoint.outputs.artifactId }}
      version:
        description: "Version from descriptor"
        value: ${{ jobs.entryPoint.outputs.version }}
      branchName:
        description: "BranchName from GITHUB"
        value: ${{ vars.GITHUB_REF_NAME }}

jobs:
  constants:
    name: Generate constants
    runs-on: ubuntu-latest
    outputs:
      job_name:
        buildJavaMaven: buildJavaMaven
        testJavaMaven: testJavaMaven
        sonarCloudScan: sonarCloudScan
        registry: registry
        deploy: deploy
    steps:
      - id: step1
        run: echo "firstword=hello" >> $GITHUB_OUTPUT