
name: entrypoint

on:
  workflow_call:
    outputs:
      constants:
        description: "Constants to use in CICD pipeline"
        value: ${{ jobs.entryPoint.outputs.constants }}
      artifactId:
        description: "ArtifactID from descriptor"
        value: ${{ jobs.entryPoint.outputs.artifactId }}
      version:
        description: "Version from descriptor"
        value: ${{ jobs.entryPoint.outputs.version }}
      branchName:
        description: "BranchName from GITHUB"
        value: ${{ vars.GITHUB_REF_NAME }}

jobs:
  entryPoint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'
      
      - name: List files
        run: cd jhflemosiaggbs/cicd-iaggbs/.github/ && ls -la

      - name: Read constants yaml
        id: constants
        uses: jbutcher5/read-yaml@main
        with:
          file: 'jhflemosiaggbs/cicd-iaggbs/.github/constants.yaml'
          key-path: '["constants"]'

      - name: Get artifactId
        id: getArtifactId
        run: |
          export ARTIFACTID=$( mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout )
          echo "artifactId=$ARTIFACTID" >> $GITHUB_OUTPUT

      - name: Get version
        id: getVersion
        run: |
          export VERSION=$( mvn help:evaluate -Dexpression=project.version -q -DforceStdout )
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      
    outputs:
      constants : ${{ steps.constants.outputs.data }}
      artifactId: ${{ steps.getArtifactId.outputs.artifactId }}
      version   : ${{ steps.getVersion.outputs.version }}
      branchName: ${{ steps.branchName.outputs.current_branch }}
