
name: entrypoint 

on:
  workflow_call:
    inputs:
      recipe:
        required: true
        type: string
      provider:
        required: true
        type: string

jobs:
  entryPoint:
    if: ${{ inputs.recipe == 'node' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'
      - name: Get artifactId
        id: getArtifactId
        run: |
          export ARTIFACTID=$( mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout )
          echo "artifactId=$ARTIFACTID" >> $GITHUB_OUTPUT
      - name: Get version
        id: getVersion
        run: |
          export VERSION=$( mvn help:evaluate -Dexpression=project.version -q -DforceStdout )
          echo "version=$VERSION" >> $GITHUB_OUTPUT
    outputs:
      artifactId: ${{ steps.getArtifactId.outputs.artifactId }}
      version   : ${{ steps.getVersion.outputs.version }}
      branchName: ${{ github.ref_name }}
  
  test:
    if: ${{ inputs.recipe == 'node' }}
    needs: [entrypoint]
    uses: jhflemosiaggbs/cicd-iaggbs/.github/workflows/testJavaMaven.yaml@develop
  
  testNode:  
    if: ${{ inputs.recipe == 'node' }}
    needs: [entrypoint]
    uses: jhflemosiaggbs/cicd-iaggbs/.github/workflows/testJavaMaven.yaml@develop
  
  build:
    if: ${{ inputs.recipe == 'node' }}
    needs: [entryPoint]
    uses: jhflemosiaggbs/cicd-iaggbs/.github/workflows/buildJavaMaven.yaml@develop
  #
  #sonarScan:
  #  needs: [entryPoint, test, build]
  #  uses: jhflemosiaggbs/cicd-iaggbs/.github/workflows/sonarCloudScan.yaml@develop
  #  secrets: inherit
  #  with:
  #    artifactId: ${{ needs.entrypoint.outputs.artifactId }}
  #    version : ${{ needs.entrypoint.outputs.version }}
#
  #registry:
  #  needs: [entryPoint, sonarScan]
  #  uses: jhflemosiaggbs/cicd-iaggbs/.github/workflows/registryS3.yaml@develop
  #  secrets: inherit
  #  with:
  #    artifactId: ${{ needs.entrypoint.outputs.artifactId }}
  #    version : ${{ needs.entrypoint.outputs.version }}
  #    branchName : ${{ needs.entrypoint.outputs.branchName }}
#
  #deploy:
  #  needs: [entryPoint, registry]
  #  uses: jhflemosiaggbs/cicd-iaggbs/.github/workflows/deployLambda.yaml@develop
  #  secrets: inherit
  #  with:
  #    artifactId: ${{ needs.entrypoint.outputs.artifactId }}
  #    version : ${{ needs.entrypoint.outputs.version }}
  #    branchName : ${{ needs.entrypoint.outputs.branchName }}