
name: registryS3

on:
  workflow_call:
    inputs:
      artifactId:
        required: true
        type: string
      version:
        required: true
        type: string
      branchName:
        required: true
        type: string

jobs:
  registryS3:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: java-artifact
      
      - name: Registry to S3
        uses: hkusu/s3-upload-action@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'eu-west-2'
          aws-bucket: 's3b-iagcih-${{ inputs.artifactId }}-bucket'
          file-path: './${{ inputs.artifactId }}.jar'
          destination-dir: '/${{ inputs.branchName }}/${{ inputs.version }}'